### PR TITLE
Create product relationship

### PR DESCRIPTION
**Pull request by henryhu-zh**
Added create recommendation function in `routes.py`
Uncommented test_get_recommendation in `test_routes.py`

### CODE REVIEW

**Comment by Ruochen1105** [comment]
Missing test cases for "Create": [github.com/nyu-devops/lab-flask-tdd/blob/master/tests/test_routes.py](https://github.com/nyu-devops/lab-flask-tdd/blob/91420f2498faa8461ba2f63796f2a7b13aef1071/tests/test_routes.py#L136-L161)

**Review by Ruochen1105 — CHANGES_REQUESTED** [review]
Missing test cases for "Create": [github.com/nyu-devops/lab-flask-tdd/blob/master/tests/test_routes.py](https://github.com/nyu-devops/lab-flask-tdd/blob/91420f2498faa8461ba2f63796f2a7b13aef1071/tests/test_routes.py#L136-L161)

**Comment by OlekKapera** [comment]
I also found a few things that could be improved: 
1. branches should start with `feature/` prefix, so your branch should have been named `feature/create-product-relationship`
2. As Ruochen mentioned you didn't add tests for your endpoint, meaning you didn't follow Test Driven Development.
3. When I run tests, I see only 90% coverage (hopefully it will be fixed by adding `create` tests).
4. When I run tests, there is an error in the code and in crashes (see screenshot)
image

**Review by OlekKapera — CHANGES_REQUESTED** [review]
I also found a few things that could be improved: 
1. branches should start with `feature/` prefix, so your branch should have been named `feature/create-product-relationship`
2. As Ruochen mentioned you didn't add tests for your endpoint, meaning you didn't follow Test Driven Development.
3. When I run tests, I see only 90% coverage (hopefully it will be fixed by adding `create` tests).
4. When I run tests, there is an error in the code and in crashes (see screenshot)
image

**Comment by Ruochen1105** [comment]
> I also found a few things that could be improved:
> 
>     1. branches should start with `feature/` prefix, so your branch should have been named `feature/create-product-relationship`
> 
>     2. As Ruochen mentioned you didn't add tests for your endpoint, meaning you didn't follow Test Driven Development.
> 
>     3. When I run tests, I see only 90% coverage (hopefully it will be fixed by adding `create` tests).
> 
>     4. When I run tests, there is an error in the code and in crashes (see screenshot)
> 
> 
> image

Is it okay for Zhihan to leave the erroneous test case commented in this PR? The test case should have been covered by me (and was commented out because there was no “Create” at that time) , and I can work on the test case as well as add one for the “sad path.”

**Comment by OlekKapera** [comment]
> Is it okay for Zhihan to leave the erroneous test case commented in this PR? The test case should have been covered by me (and was commented out because there was no “Create” at that time) , and I can work on the test case as well as add one for the “sad path.”

Good idea! I created a bug issue for that #18

**Comment by henryhu-zh** [comment]
@OlekKapera @Ruochen1105 
Thanks for pointing out these issues! I'm fixing them now.

**Review by Ruochen1105 — APPROVED** [review]

**Review by OlekKapera — APPROVED** [review]

**Pull request merged**
